title: 'UCSF C4 Cluster'
theme: jekyll-theme-minimal

google_analytics: UA-128646955-1

organization:
  name: "CBI"
  url: "https://cbi.ucsf.edu/"

cluster:
  name: "C4"
  nickname: "C4"
  version: "0.1"
  email_admin: harry.putnam@ucsf.edu
  email_support: harry.putnam@ucsf.edu

login:
  name: "c4-log1"
  hostname: "c4-log1.ucsf.edu"
  ip: "169.230.134.135"
devel:
  name: "c4-dev1"
  hostname: "c4-dev1"
  ip: "NA.NA.NA.NA"
transfer:
  name: "c4-dt1"
  hostname: "c4-dt1.ucsf.edu"
  ip: "169.230.134.197"


login1:
  name: "c4-log1"
  hostname: "c4-log1.ucsf.edu"
  ip: "169.230.134.135"
login2:
  name: "c4-log2"
  hostname: "c4-log2.ucsf.edu"
  ip: "169.230.134.136"
dev1:
  name: "c4-dev1"
  hostname: "c4-dev1"
  ip: "NA.NA.NA.NA"
dev2:
  name: "c4-dev2"
  hostname: "c4-dev2"
  ip: "NA.NA.NA.NA"
dev3:
  name: "not-yet-available-c4-dev3"
  hostname: "not-yet-available-c4-dev3.ucsf.edu"
  ip: "NA.NA.NA.NA"
gpudev1:
  name: "not-yet-available-c4-gpudev1"
  hostname: "not-yet-available-c4-gpudev1.ucsf.edu"
  ip: "NA.NA.NA.NA"
transfer1:
  name: "c4-dt1"
  hostname: "c4-dt1.ucsf.edu"
  ip: "169.230.134.197"
transfer2:
  name: "not-yet-available-c4-dt2"
  hostname: "non-yet-available-c4-dt2.ucsf.edu"
  ip: "NA.NA.NA.NA"

assets:
  status_root_path: "https://raw.githubusercontent.com/UCSF-HPC/wynton-slash/master/wynton/docs"

plugins:
  - jekyll-target-blank
