title: 'UCSF C4 Cluster'
repository: UCSF-CBI/c4
theme: jekyll-theme-minimal

google_analytics: UA-56080795-1

organization:
  name: "CBI"
  url: "https://cbi.ucsf.edu/"

division:
  name: "HDFCCC"
  url: "https://cancer.ucsf.edu/"

user:
  name: "alice"
  email: "alice.aliceson@ucsf.edu"
  home: "/c4/home/alice"
  labfolder: "/boblab"

cluster:
  name: "C4"
  nickname: "C4"
  version: ""
  email_admin: harry.putnam@ucsf.edu
  email_support: harry.putnam@ucsf.edu
  status: ok

path:
  global_root: /c4
  global_scratch: /c4/scratch
  cbi_software: /software/c4/cbi/software
  
login:
  name: "c4-log1"
  hostname: "c4-log1.ucsf.edu"
  ip: "169.230.134.135"
devel:
  name: "c4-dev1"
  hostname: "c4-dev1"
  ip: "NA.NA.NA.NA"
transfer:
  name: "c4-dt1"
  hostname: "c4-dt1.ucsf.edu"
  ip: "169.230.134.197"


login1:
  name: "c4-log1"
  hostname: "c4-log1.ucsf.edu"
  ip: "169.230.134.135"
login2:
  name: "c4-log2"
  hostname: "c4-log2.ucsf.edu"
  ip: "169.230.134.136"
dev1:
  name: "c4-dev1"
  hostname: "c4-dev1"
  ip: "NA.NA.NA.NA"
dev2:
  name: "c4-dev2"
  hostname: "c4-dev2"
  ip: "NA.NA.NA.NA"
dev3:
  name: "c4-dev3"
  hostname: "c4-dev3"
  ip: "NA.NA.NA.NA"
gpudev1:
  name: "not-yet-available-c4-gpudev1"
  hostname: "not-yet-available-c4-gpudev1.ucsf.edu"
  ip: "NA.NA.NA.NA"
transfer1:
  name: "c4-dt1"
  hostname: "c4-dt1.ucsf.edu"
  ip: "169.230.134.197"
transfer2:
  name: "c4-dt2"
  hostname: "c4-dt2.ucsf.edu"
  ip: "169.230.134.240"

globus:
  name: "UCSF#C4-HPC"
  uuid: a436389c-0e5a-11eb-81b1-0e2f230cc907

assets:
  status_root_path: ""

plugins:
  - jekyll-target-blank
