title: 'UCSF HPC: Wynton'
theme: jekyll-theme-minimal
foo: 'hello world!'
login_name: "wynton"
login_node: "wynton.ucsf.edu"
login_ip: "169.230.nnn.nnn"
login:
  name: "wynton"
  hostname: "wynton.ucsf.edu"
  ip: "169.230.nnn.nnn"
