title: 'UCSF Wynton HPC Cluster'
theme: jekyll-theme-minimal

google_analytics: UA-128646955-1

login:
  name: "wynlog2"
  hostname: "wynlog2.cc.ucsf.edu"
  ip: "169.230.134.15"
devel:
  name: "qb3-dev3"
  hostname: "qb3-dev3"
  ip: "172.26.32.8"

login1:
  name: "wynlog1"
  hostname: "wynlog1.compbio.ucsf.edu"
  ip: "169.230.126.77"
login2:
  name: "wynlog2"
  hostname: "wynlog2.cc.ucsf.edu"
  ip: "169.230.134.15"
dev1:
  name: "qb3-dev1"
  hostname: "qb3-dev1"
  ip: "172.26.32.2"
dev2:
  name: "qb3-dev2"
  hostname: "qb3-dev2"
  ip: "172.26.32.7"
dev3:
  name: "qb3-dev3"
  hostname: "qb3-dev3"
  ip: "172.26.32.8"
transfer:
  name: "wyndt1"
  hostname: "wyndt1.compbio.ucsf.edu"
  ip: "169.230.126.58"
transfer_old:
  name: "wynlog1"
  hostname: "wynlog1.compbio.ucsf.edu"
  ip: "169.230.126.77"

specs:
  nodes: 195
  physical_cores: 4668
  gpus: 58
  gpu_nodes: 24
  
  ## CPU [GHz]:
  cpu_min: 2.6
  cpu_max: 3.4

  ## RAM [GiB]:
  ram_min: 48
  ram_max: 768
  
  ## Disk /swap [GiB]:
  swap_min: 4
  swap_max: 4

  ## Local /tmp [GiB]:
  local_tmp_size_min: 4
  local_tmp_size_max: 4

  ## Local /scratch [TiB]:
  local_scratch_size_min: 0.1
  local_scratch_size_max: 1.8
  
  ## Global /wynton/scratch [TiB]:
  global_scratch_size_total: 492
  
  ## NetApp home [TiB]:
  netapp_home_size_total: 20
  
  ## User home [TiB]:
  home_size_total: 383

  ## Deprecated fields - use above instead /HB 2019-03-11
  cpu_range: "2.6-3.4 GHz"
  ram_range: "48-768 GiB"
  swap_range: "4 GiB"
  local_tmp_size: "4 GiB"
  local_scratch_size_range: "0.1-1.8 TiB"
  global_scratch_size: "492 TiB"
  netapp_home_size: "20 TiB"
  home_size: "383 TiB"
  
assets:
  status_root_path: "https://raw.githubusercontent.com/UCSF-HPC/wynton-slash/master/wynton/docs"
