title: 'UCSF HPC: Wynton'
theme: jekyll-theme-minimal
foo: 'hello world!'
login:
  name: "login"
  hostname: "login.wynton.ucsf.edu"
  ip: "169.230.nnn.nnn"
transfer:
  name: "transfer"
  hostname: "transfer.wynton.ucsf.edu"
  ip: "169.230.nnn.nnn"
