title: 'UCSF Wynton HPC Cluster'
theme: jekyll-theme-minimal
login:
  name: "wynlog2"
  hostname: "wynlog2.cc.ucsf.edu"
  ip: "169.230.134.15"
login1:
  name: "wynlog1"
  hostname: "wynlog1.compbio.ucsf.edu"
  ip: "169.230.126.77"
login2:
  name: "wynlog2"
  hostname: "wynlog2.cc.ucsf.edu"
  ip: "169.230.134.15"
devel:
  name: "qb3-dev1"
  hostname: "qb3-dev1"
  ip: "172.26.32.2"
transfer:
  name: "wyndt1"
  hostname: "wyndt1.compbio.ucsf.edu"
  ip: "169.230.126.58"
transfer_old:
  name: "wynlog1"
  hostname: "wynlog1.compbio.ucsf.edu"
  ip: "169.230.126.77"
specs:
  nodes: 86
  physical_cores: 1816
  gpus: 42
  gpu_nodes: 16
  cpu_range: "2.6-3.4 GHz"
  ram_range: "48-768 GiB"
  local_scratch_size_range: "0.1-1.8 TiB"
  local_tmp_size: "4 GiB"
