title: 'UCSF HPC: Wynton'
theme: jekyll-theme-minimal
login:
  name: "login"
  hostname: "login.wynton.ucsf.edu"
  ip: "169.230.nnn.nnn"
transfer:
  name: "transfer"
  hostname: "transfer.wynton.ucsf.edu"
  ip: "169.230.nnn.nnn"
interactive:
  name: "interactive"
  hostname: "interactive.wynton.ucsf.edu"
  ip: "169.230.nnn.nnn"
