title: 'UCSF Wynton HPC Cluster'
theme: jekyll-theme-minimal
login:
  name: "wynlog1"
  hostname: "wynlog1.compbio.ucsf.edu"
  ip: "169.230.126.77"
login2:
  name: "wynlog2"
  hostname: "wynlog2.cc.ucsf.edu"
  ip: "169.230.134.15"
interactive:
  name: "qb3-int1"
  hostname: "qb3-int1"
  ip: "172.26.32.2"
transfer_todo:
  name: "transfer"
  hostname: "transfer.wynton.ucsf.edu"
  ip: "169.230.nnn.nnn"
transfer:
  name: "wynlog1"
  hostname: "wynlog1.compbio.ucsf.edu"
  ip: "169.230.126.77"
