on: [push, pull_request]

name: 'Spell check'

jobs:
  spelling:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    runs-on: ubuntu-latest
    
    name: spelling

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::spelling
          needs: check

      - name: Spell check README and Markdown files
        run: |
          make spell
