on: [push, pull_request]

name: Usernames

jobs:
  ShellCheck:
    runs-on: ubuntu-18.04
    name: Usernames
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2

    - name: usernames
      run: |
        make check-usernames

