on: [push, pull_request]

name: 'YAML check'

jobs:
  yaml:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    runs-on: ubuntu-latest
    
    name: spelling

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install required R packages
        run: |
          install.packages("yaml")
        shell: Rscript {0}

      - name: Validate YAML files
        run: |
          make yaml-check
